from packages.api.main import app


def test_expected_route_paths_present():
    paths = {route.path for route in app.routes}
    expected = {
        "/health",
        "/api/dashboard",
        "/api/status/history",
        "/api/device/settings",
        "/api/consumption/history",
        "/api/prices",
        "/api/weather",
        "/api/plans",
        "/api/plans/{plan_id}",
        "/api/overrides",
        "/api/overrides/{override_id}",
        "/api/settings",
        "/api/comfort-schedule",
        "/api/comfort-schedule/learned",
        "/api/comfort-schedule/apply-learned",
        "/api/audit",
        "/api/logs",
        "/api/currency",
        "/api/time-format",
        "/api/indoor-temp",
        "/api/indoor-temp/latest",
        "/api/smartthings/devices",
        "/api/smartthings/oauth/authorize",
        "/api/smartthings/oauth/callback",
        "/api/smartthings/oauth/status",
        "/api/smartthings/oauth/disconnect",
        "/api/comfort-model/status",
        "/api/comfort-model/train",
        "/api/comfort-model/predict",
        "/api/optimizer/status",
        "/api/ml/train",
        "/api/thermal/status",
        "/api/thermal/calibrate",
        "/api/optimize-now",
        "/api/thermal/curve",
        "/api/thermal/indoor-forecast",
        "/api/poll-now",
        "/api/test-connection",
        "/api/faults",
        "/api/faults/{fault_id}/resolve",
        "/api/cop/history",
        "/api/cop/stats",
        "/api/cop/compute",
        "/api/compressor/activity",
    }
    assert expected.issubset(paths)
