# https://packaging.python.org/tutorials/packaging-projects/

[build-system]
requires = [
    "setuptools>=77.0.3",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "aioaquarea"
version = "1.0.9"
authors = [
  { name="Carlos J. Aliaga", email="dev@cjaliaga.net" },
]
description = "Asynchronous library to control Panasonic Aquarea devices"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
dependencies = [
  "aiohttp>=3.14.3,<4",
  'StrEnum>=0.4.15; python_version < "3.11"',
  "beautifulsoup4>=4.12,<5",
]

[project.optional-dependencies]
dev = [
  "black>=24.0",
  "build>=1.2",
  "isort>=5.13",
  "pylint>=3.0",
  "pytest>=8.0",
  "pytest-asyncio>=0.23",
  "twine>=5.0",
]

[project.urls]
"Homepage" = "https://github.com/cjaliaga/aioaquarea"
"Bug Tracker" = "https://github.com/cjaliaga/aioaquarea/issues"

[tool.setuptools.package-data]
aioaquarea = ["py.typed"]

[tool.black]
target-version = ["py310"]

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"
# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
